steps:
  FCT_ORDERS-b7ab379c-8a5a-424b-904e-df9600595bde:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      deployEnabled: true
      description: Orders data as defined by TPC-H
      isMultisource: false
      locationName: TRAINING
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - appliedColumnTests:
              hasNull: false
              isDistinct: true
            columnReference:
              columnCounter: a1e05b12-12f1-466a-9de5-1a11ff87e082
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: NUMBER
            description: ""
            hashColumns: []
            hashDetails: null
            name: DIM_ORDERS_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: e53d908f-5a55-4bd5-b749-6f7ea83e35e5
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: ""
          - appliedColumnTests:
              hasNull: false
              isDistinct: true
            columnReference:
              columnCounter: 0d540f71-9d5b-488f-8565-429e407b98b9
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_ORDERKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 19abd013-a260-443a-8497-485b938b1da7
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: ""
          - appliedColumnTests:
              hasNull: false
              isDistinct: true
            columnReference:
              columnCounter: 3e7396f6-55bd-4077-a3ad-97c3c8ee7962
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_CUSTKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 810c4c12-868e-499d-9dbb-d7ac9f4c27cd
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: ""
          - appliedColumnTests:
              hasNull: false
              isDistinct: false
            columnReference:
              columnCounter: b0735705-eced-46fe-8d54-56788c735525
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: VARCHAR(1)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_ORDERSTATUS
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 44bccef2-5b5e-43d6-aa09-a88924ed54d2
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: ""
          - appliedColumnTests:
              hasNull: false
              isDistinct: false
            columnReference:
              columnCounter: 5115f8d0-9176-4137-9b97-e4a2842dbe46
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: NUMBER(12,2)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_TOTALPRICE
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: f202f13f-d05f-4a90-926f-4a73e5503b61
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: ""
          - appliedColumnTests:
              hasNull: false
              isDistinct: false
            columnReference:
              columnCounter: 2e36f73b-755e-4b88-a87a-d7020482f7f6
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: DATE
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_ORDERDATE
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 8b837f37-a950-42ae-acea-68a5cfb969fe
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: ""
          - appliedColumnTests:
              hasNull: false
              isDistinct: false
            columnReference:
              columnCounter: 389728c3-8e28-44e5-b399-f52c5c47f5fb
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: VARCHAR(15)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_ORDERPRIORITY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 8228a005-1726-435a-b03b-c3419ebb8322
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: ""
          - appliedColumnTests:
              hasNull: false
              isDistinct: false
            columnReference:
              columnCounter: 23fdc4d4-4bc3-409e-ad11-9442a199b435
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: VARCHAR(15)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_CLERK
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 8c623e17-f709-4d31-8e67-f0ef22f0ec87
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: ""
          - appliedColumnTests:
              hasNull: false
              isDistinct: false
            columnReference:
              columnCounter: 5a26c310-64f2-48fc-bcad-dca71003629e
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_SHIPPRIORITY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 4a9fc48b-932e-4467-85a2-d0b81a0a97bf
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: ""
          - appliedColumnTests:
              hasNull: true
              isDistinct: false
            columnReference:
              columnCounter: e484c78a-9604-433c-ab50-8f0a994c895d
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: VARCHAR(79)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_COMMENT
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: bf21f3cd-1f22-43ab-bee8-fc380812a2ec
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: "{{UPPER_CASE('\"TEST\".\"O_COMMENT\"')}}"
          - appliedColumnTests:
              hasNull: false
              isDistinct: false
            columnReference:
              columnCounter: e77866e1-824a-4e5c-b67b-80f51009af70
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: NUMBER
            description: ""
            hashColumns: []
            hashDetails: null
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 0a2baf6f-ccb6-4102-9ddc-ebfed94a7d70
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: ""
          - appliedColumnTests:
              hasNull: false
              isDistinct: false
            columnReference:
              columnCounter: 5338f0a8-cfc7-4303-b715-5034d383d362
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: VARCHAR
            description: ""
            hashColumns: []
            hashDetails: null
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: afdcb031-73cc-4c9f-b40a-aadcca11d477
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: ""
          - appliedColumnTests:
              hasNull: false
              isDistinct: false
            columnReference:
              columnCounter: c92dcf7c-484b-4194-8d9b-f9a8194f5c81
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: TIMESTAMP
            description: ""
            hashColumns: []
            hashDetails: null
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: a9b868b8-2772-491a-81be-48f10a771d12
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: ""
          - appliedColumnTests:
              hasNull: false
              isDistinct: false
            columnReference:
              columnCounter: e999abd9-6b69-4c66-a730-865678d27d79
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            dataType: TIMESTAMP
            description: ""
            hashColumns: []
            hashDetails: null
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 56441a45-95ba-4645-bb7b-49ebc7661009
                    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests:
              hasNull: false
              isDistinct: false
            columnReference:
              columnCounter: edd2f5de-c28f-4b79-9e65-d32d5f7ad355
              stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs:
          - hasNull
          - isDistinct
        sourceMapping:
          - aliases:
              DIM_CUSTOMER: 19d5269a-c011-443d-a574-5b277d758064
              DIM_ORDERS: dbf94eb1-6d57-4073-8437-40fb22485846
            customSQL:
              customSQL: ""
            dependencies:
              - locationName: TRAINING
                nodeName: DIM_CUSTOMER
              - locationName: TRAINING
                nodeName: DIM_ORDERS
            join:
              joinCondition: |-
                FROM {{ ref('TRAINING', 'DIM_ORDERS') }} "DIM_ORDERS"
                LEFT JOIN {{ ref('TRAINING','DIM_CUSTOMER') }} "DIM_CUSTOMER"
                ON "DIM_CUSTOMER"."C_CUSTKEY"="DIM_ORDERS"."O_CUSTKEY"
            name: FCT_ORDERS
            noLinkRefs: []
      name: FCT_ORDERS
      overrideSQL: false
      schema: ""
      sqlType: Fact
      type: sql
    stepCounter: b7ab379c-8a5a-424b-904e-df9600595bde
