steps:
  DIM_ORDERS-dbf94eb1-6d57-4073-8437-40fb22485846:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      deployEnabled: true
      description: Orders data as defined by TPC-H
      isMultisource: false
      locationName: TRAINING
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: e53d908f-5a55-4bd5-b749-6f7ea83e35e5
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            hashColumns: []
            isSurrogateKey: true
            name: DIM_ORDERS_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: 19abd013-a260-443a-8497-485b938b1da7
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_ORDERKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: dc456a02-1410-487d-ba9f-572e5468b997
                    stepCounter: dc69005a-0513-4053-bee7-ee78f9c02a00
                transform: ""
          - columnReference:
              columnCounter: 810c4c12-868e-499d-9dbb-d7ac9f4c27cd
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            isBusinessKey: true
            name: O_CUSTKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: c6a1a302-72ba-4fe4-bf9f-84e8e8b8b0ab
                    stepCounter: dc69005a-0513-4053-bee7-ee78f9c02a00
                transform: ""
          - columnReference:
              columnCounter: 44bccef2-5b5e-43d6-aa09-a88924ed54d2
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            dataType: VARCHAR(1)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_ORDERSTATUS
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 82cfcd58-917c-4e3e-b836-414dee1abc05
                    stepCounter: dc69005a-0513-4053-bee7-ee78f9c02a00
                transform: ""
          - columnReference:
              columnCounter: f202f13f-d05f-4a90-926f-4a73e5503b61
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            dataType: NUMBER(12,2)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_TOTALPRICE
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 04dd4530-2f74-43bc-96c1-7b8230481446
                    stepCounter: dc69005a-0513-4053-bee7-ee78f9c02a00
                transform: ""
          - columnReference:
              columnCounter: 8b837f37-a950-42ae-acea-68a5cfb969fe
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            dataType: DATE
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_ORDERDATE
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 9aa0ccdc-d66d-4a92-8248-468e3f8a81c4
                    stepCounter: dc69005a-0513-4053-bee7-ee78f9c02a00
                transform: ""
          - columnReference:
              columnCounter: 8228a005-1726-435a-b03b-c3419ebb8322
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            dataType: VARCHAR(15)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_ORDERPRIORITY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: d59c7885-a6e9-4c60-b34f-b3f4a89e417b
                    stepCounter: dc69005a-0513-4053-bee7-ee78f9c02a00
                transform: ""
          - columnReference:
              columnCounter: 8c623e17-f709-4d31-8e67-f0ef22f0ec87
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            dataType: VARCHAR(15)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_CLERK
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: d3906074-b1de-441d-8e71-c85c2f7546a8
                    stepCounter: dc69005a-0513-4053-bee7-ee78f9c02a00
                transform: ""
          - columnReference:
              columnCounter: 4a9fc48b-932e-4467-85a2-d0b81a0a97bf
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_SHIPPRIORITY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: d4c75a98-6972-489d-bcc4-4ce30c7aa3db
                    stepCounter: dc69005a-0513-4053-bee7-ee78f9c02a00
                transform: ""
          - columnReference:
              columnCounter: bf21f3cd-1f22-43ab-bee8-fc380812a2ec
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            dataType: VARCHAR(79)
            description: ""
            hashColumns: []
            hashDetails: null
            name: O_COMMENT
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 9997f1c0-b76c-45a3-990d-13ec65436469
                    stepCounter: dc69005a-0513-4053-bee7-ee78f9c02a00
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 0a2baf6f-ccb6-4102-9ddc-ebfed94a7d70
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: afdcb031-73cc-4c9f-b40a-aadcca11d477
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: a9b868b8-2772-491a-81be-48f10a771d12
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 56441a45-95ba-4645-bb7b-49ebc7661009
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: f98948c4-09f4-4107-82af-53e5f3d4852b
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: cef26f76-82ce-4eaf-a29e-643db027ada8
              stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: TRAINING
                nodeName: STG_ORDERS
            join:
              joinCondition: FROM {{ ref('TRAINING', 'STG_ORDERS') }} "STG_ORDERS"
            name: DIM_ORDERS
            noLinkRefs: []
      name: DIM_ORDERS
      overrideSQL: false
      schema: ""
      sqlType: Dimension
      type: sql
    stepCounter: dbf94eb1-6d57-4073-8437-40fb22485846
