steps:
  STG_CUSTOMER-a88effa6-9b91-47e2-8c9c-0f68a5e9f5f8:
    operation:
      config:
        insertStrategy: INSERT
        postSQL: ""
        preSQL: ""
        testsEnabled: true
        truncateBefore: true
      database: ""
      deployEnabled: true
      description: Customer data as defined by TPC-H
      isMultisource: false
      locationName: TRAINING
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - columnReference:
              columnCounter: 379995f3-313e-4768-8cc6-c3cbe18ee726
              stepCounter: a88effa6-9b91-47e2-8c9c-0f68a5e9f5f8
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            isBusinessKey: true
            name: C_CUSTKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 80167459-6b48-4233-aaff-ebefd71a3e67
                    stepCounter: b5bba575-bf27-4579-b30d-63c1d4488246
                transform: ""
          - columnReference:
              columnCounter: 2c16ee19-65f9-47a9-ae8b-693a201c7eb7
              stepCounter: a88effa6-9b91-47e2-8c9c-0f68a5e9f5f8
            dataType: VARCHAR(25)
            description: Customer Name
            hashColumns: []
            hashDetails: null
            name: C_NAME
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: f9457481-330c-45e7-9562-ba94405c4c9e
                    stepCounter: b5bba575-bf27-4579-b30d-63c1d4488246
                transform: ""
          - columnReference:
              columnCounter: e4e98192-cb17-4c42-86e7-7c94433c0716
              stepCounter: a88effa6-9b91-47e2-8c9c-0f68a5e9f5f8
            dataType: VARCHAR(40)
            description: ""
            hashColumns: []
            hashDetails: null
            isChangeTracking: true
            name: C_ADDRESS
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 5d020eba-c869-46d0-b94f-27125798b978
                    stepCounter: b5bba575-bf27-4579-b30d-63c1d4488246
                transform: ""
          - columnReference:
              columnCounter: 0ede63ff-66c4-40c6-abfb-e97772b77e98
              stepCounter: a88effa6-9b91-47e2-8c9c-0f68a5e9f5f8
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: C_NATIONKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 6668b45c-62f9-4f3e-84b8-ef739137e7c3
                    stepCounter: b5bba575-bf27-4579-b30d-63c1d4488246
                transform: ""
          - columnReference:
              columnCounter: 9c5f10fd-02f1-4e5a-97fd-a4cc11af88b6
              stepCounter: a88effa6-9b91-47e2-8c9c-0f68a5e9f5f8
            dataType: VARCHAR(15)
            description: ""
            hashColumns: []
            hashDetails: null
            isChangeTracking: true
            name: C_PHONE
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 69b6384a-a6a4-45df-b88d-64f49e5f06ad
                    stepCounter: b5bba575-bf27-4579-b30d-63c1d4488246
                transform: ""
          - columnReference:
              columnCounter: fb87ef5f-c060-4fbc-a3c1-4ba9c0490299
              stepCounter: a88effa6-9b91-47e2-8c9c-0f68a5e9f5f8
            dataType: NUMBER(12,2)
            description: ""
            hashColumns: []
            hashDetails: null
            name: C_ACCTBAL
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: f57d51a6-13aa-4fa4-bbea-e09d9db550d4
                    stepCounter: b5bba575-bf27-4579-b30d-63c1d4488246
                transform: ""
          - columnReference:
              columnCounter: 665dd0ce-5e0e-430e-ac0e-0526c434aae1
              stepCounter: a88effa6-9b91-47e2-8c9c-0f68a5e9f5f8
            dataType: VARCHAR(10)
            description: ""
            hashColumns: []
            hashDetails: null
            name: C_MKTSEGMENT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: aab2e3e7-46f4-4deb-a03b-63d68553feca
                    stepCounter: b5bba575-bf27-4579-b30d-63c1d4488246
                transform: ""
          - columnReference:
              columnCounter: 4f56c30f-a59d-4f5a-84a3-a598b8e29356
              stepCounter: a88effa6-9b91-47e2-8c9c-0f68a5e9f5f8
            dataType: VARCHAR(117)
            description: ""
            hashColumns: []
            hashDetails: null
            name: C_COMMENT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: f7364d3d-f2b7-43a6-884e-f7d87892944a
                    stepCounter: b5bba575-bf27-4579-b30d-63c1d4488246
                transform: ""
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: COALESCE
                nodeName: CUSTOMER
            join:
              joinCondition: FROM {{ ref('COALESCE', 'CUSTOMER') }} "CUSTOMER"
            name: STG_CUSTOMER
            noLinkRefs: []
      name: STG_CUSTOMER
      overrideSQL: false
      schema: ""
      sqlType: Stage
      type: sql
    stepCounter: a88effa6-9b91-47e2-8c9c-0f68a5e9f5f8
